version: '3.8'
services:
  <SITE_NAME>:
    container_name: <SITE_NAME>
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "<HTTP_PORT>:80"
      - "<HTTP_SSL_PORT>:443"
    env_file:
      - .env
    volumes:
      - ./<WEB_ROOT>:/var/www/html
      - ./config/php/php-dev.ini:/etc/php/8/apache2/php.ini
    networks:
      - <NETWORK>
volumes:
  <SITE_NAME>:

networks:
  <NETWORK>:
    name: <NETWORK>
    external: true
