version: '3.8'
services:
  sites_db:
    container_name: sites_db
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    ports:
      - "13306:3306"
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - sites_db
  sites_db_pma:
    container_name: sites_db_pma
    image: phpmyadmin
    restart: always
    ports:
      - 18080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - sites_db
volumes:
  sites_db:

networks:
  sites_db:
    name: sites_db
    external: true
